Week 3 bash scripting assignment
b-husein/husein-bajrektarevic-devops-mentorship pull request #3
Opened 2023-03-09 07:49 UTC by b-husein

_The main task was to read ch. 13 - 16 from the book - **Linux Command Line and Shell Scripting Bible, 3rd Edition**, document and execute scripts from these chapters and take screenshots that will be uploaded to PR._

Link to ticket: https://github.com/allops-solutions/devops-aws-mentorship-program/issues/16

I made following steps: 

   - [x] Read Ch. 13 - 16 in Linux Command Line and Shell scripting book.
   - [x] Go through scripts in ch. 13 and execute them.
   - [x] Go through scripts in ch. 14 and execute them.
   - [x] Go through scripts in ch. 15 and execute them.
   - [x] Go through scripts in ch. 16 and execute them.
   - [x] Take screenshots of executed scripts.
   - [x] Create PR - post screenshots inside of it.
   - [x] Post PR as a comment on the ticket.
   
  Screenshots of executed scripts are attached below: 
  
  **1 - Ch. 13 executed scripts screenshots:** 
    
![ch13-scripts01-08](https://user-images.githubusercontent.com/40772085/223954022-9d3f962d-c2f9-4173-9ce8-1071788ac698.png)
  
![ch13-scripts09-16](https://user-images.githubusercontent.com/40772085/223954069-255b953f-1bd0-42e5-bdfb-03e22eb4daab.png)

![ch13-scripts17-24](https://user-images.githubusercontent.com/40772085/223954127-7913aa9c-1944-445e-921b-7ab1917fbeca.png)
  
![ch13-scripts25-32](https://user-images.githubusercontent.com/40772085/223954182-c84323bf-0ced-42b0-bcfe-cdbaa68917a7.png)

![sch13-scripts33-34](https://user-images.githubusercontent.com/40772085/223954220-4dc899ba-d6ee-4376-a640-f3f289e1d4d9.png)

**2 - Ch. 14 executed scripts screenshots:**

![ch14-scripts-01-08](https://user-images.githubusercontent.com/40772085/223954426-bc37485b-f3fa-47f5-b60e-5fd70bef37d0.png)

![ch14-scripts-09-16](https://user-images.githubusercontent.com/40772085/223954467-673b270c-7105-4290-b694-fbde521c510a.png)

![ch14-scripts-17-24](https://user-images.githubusercontent.com/40772085/223954543-d9166cf3-b9c7-4e35-bae3-5b3ce5f544d6.png)

![ch14-scripts-25-30](https://user-images.githubusercontent.com/40772085/223954590-951be148-a4ab-448d-81cd-b4c011d3bb27.png)

**3 - Ch. 15 executed scripts screenshots:**

![ch15-scripts-01-08](https://user-images.githubusercontent.com/40772085/223954789-1a434002-9507-4ec5-b204-8320d22d8f43.png)

![ch15-scripts-09-16](https://user-images.githubusercontent.com/40772085/223954849-ae505b9a-abf1-4369-8edb-eefa28105b27.png)

**4 - Ch. 16 executed scripts screenshots:**

![ch16-scripts01-08](https://user-images.githubusercontent.com/40772085/223954987-b8f4a66e-f017-4057-865e-c2dbe4dd9851.png)

![ch16-scripts09-10](https://user-images.githubusercontent.com/40772085/223955030-93d16ed8-ca6c-458a-b2c6-539e711a12be.png)

_**Additional information**_

Some of the contents or original scripts from the book was changed - mostly strings and some of the outdated syntax, for example, from Ch. 14, script 1.

2023-03-09 13:10 UTC, sqlheisenberg commented
it would be probably better to put all chapter scripts inside directory week-3 so that you have a consistent dir organization 
week-2 - work from week 2
week-3 - work from week 3

2023-03-09 13:11 UTC, sqlheisenberg requested changes
Please take a look on my comments above

2023-03-09 13:19 UTC, b-husein commented
@sqlheisenberg done, please review.

2023-03-09 20:47 UTC, borisbradic approved these changes

2023-03-10 08:53 UTC, sqlheisenberg approved these changes

2023-03-10 09:38 UTC, merged